services:
  milo:
    build: .
    env_file: .env
    environment:
      - TZ=US/Eastern
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
      - ./service-account.json:/app/service-account.json:ro
      - ./data:/app/data
